
package lipid;

unit LipidScoreUnit;

// TODO Include here rules and queries to fulfill the practice requirements


// This is one example of rules that only prints the factorial combination of all pairs eliminating the A-A combination.
// !! TODO This rule does not include the lipid type, you shall add it.
// !! TODO Rule that states that the same lipid type with the same number of double bonds and a higher number of carbons should have a higher RT
// !! TODO
rule "Score +1 if same type, same DB, more C => higher RT"
when
    $a1 : /annotations [$rt1 : rtMin, $carbonCount1 : lipid.getCarbonCount(), $doubleBondCount : lipid.getDoubleBondsCount(),$lipidType : lipid.getLipidType()]
    $a2 : /annotations [this!= $a1, lipid.getLipidType() == $lipidType,lipid.getDoubleBondsCount() == $doubleBondCount, rtMin > $rt1, lipid.getCarbonCount() > $carbonCount1]
then
    // in this case, the only change is the addition of the score, but the fact does not change so we do not break the principle of refractoriness
    $a1.addScore(1);
    $a2.addScore(1);
    // !! TODO ONLY FOR DEBUGGING
    System.out.println("✅Scored +1 higher C => higher RT: " + $a1 + " and " + $a2);
end


rule "Score +1 if same type, same C, more DB => lower RT"
when
    $a1: /annotations[
        $rt1: rtMin,
        $lipid1: lipid,
        $c: lipid.getCarbonCount(),
        $db1: lipid.getDoubleBondsCount(),
        $type: lipid.getLipidType()
    ]
    $a2: /annotations[
        this != $a1,
        lipid.getLipidType() == $type,
        lipid.getCarbonCount() == $c,
        lipid.getDoubleBondsCount() > $db1,
        rtMin < $rt1
    ]
then
    $a1.addScore(1);
    $a2.addScore(1);
    System.out.println("✅Scored +1 higher DB => lower RT:" + $a1 + " y " + $a2);
end

rule "Score +1 for same C, same DB, different type"
when
    $a1 : /annotations [
        $rt1 : rtMin,
        $lipid1 : lipid,
        $carbonCount : lipid.getCarbonCount(),
        $doubleBondCount : lipid.getDoubleBondsCount()
    ]
    $a2 : /annotations [
        this != $a1,
        $lipid2 : lipid,
        lipid.getCarbonCount() == $carbonCount,
        lipid.getDoubleBondsCount() == $doubleBondCount,
        rtMin > $rt1,
        eval($lipid2.getLipidTypeRank() > $lipid1.getLipidTypeRank())
    ]
then
    $a1.addScore(1);
    $a2.addScore(1);
    System.out.println("✅ Scored +1 for lipidtype: " + $a1 + " and " + $a2);
end



rule "Penalty -1 if same type, same DB, more C => lower RT"
when
    $a1: /annotations[
            $rt1: rtMin,
            $lipid1: lipid,
            $c: lipid.getCarbonCount(),
            $db1: lipid.getDoubleBondsCount(),
            $type: lipid.getLipidType()
        ]
     $a2: /annotations[
            this != $a1,
            lipid.getLipidType() == $type,
            lipid.getCarbonCount() > $c,
            lipid.getDoubleBondsCount() == $db1,
            rtMin < $rt1
        ]
then
    // in this case, the only change is the addition of the score, but the fact does not change so we do not break the principle of refractoriness
    $a1.addScore(-1);
    $a2.addScore(-1);
    // !! TODO ONLY FOR DEBUGGING
    System.out.println("❌ Scored -1 higher C => lower RT: " + $a1 + " and " + $a2);
end


rule "Penalty -1 if same type, same C, less DB => lower RT"
when
    $a1: /annotations[
        $rt1: rtMin,
        $lipid1: lipid,
        $c: lipid.getCarbonCount(),
        $db1: lipid.getDoubleBondsCount(),
        $type: lipid.getLipidType()
    ]
    $a2: /annotations[
        this != $a1,
        lipid.getLipidType() == $type,
        lipid.getCarbonCount() == $c,
        lipid.getDoubleBondsCount() > $db1,
        rtMin > $rt1
    ]
then
    $a1.addScore(-1);
    $a2.addScore(-1);
    System.out.println("❌ Scored -1 less DB => lower RT:" + $a1 + " y " + $a2);
end

rule "Penalty -1 for same C, same DB, different type"
when
    $a1 : /annotations [
        $rt1 : rtMin,
        $lipid1 : lipid,
        $carbonCount : lipid.getCarbonCount(),
        $doubleBondCount : lipid.getDoubleBondsCount()
    ]
    $a2 : /annotations [
        this != $a1,
        $lipid2 : lipid,
        lipid.getCarbonCount() == $carbonCount,
        lipid.getDoubleBondsCount() == $doubleBondCount,
        rtMin < $rt1,
        eval($lipid2.getLipidTypeRank() > $lipid1.getLipidTypeRank())
    ]
then
    $a1.addScore(-1);
    $a2.addScore(-1);
    System.out.println("❌ Scored -1 for lipidtype: " + $a1 + " and " + $a2);
end
